services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src
    command: npm run start:debug
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
      # debugging port
      - 9229:9229
  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - 5050:80
    depends_on:
      - postgres